apiVersion: v2
name: qa-report-platform
description: Helm chart for report platform components
type: application
version: 0.0.1
appVersion: 1.0.0
icon: https://groundzero.solutions
dependencies:
- name: logstash
  repository: "https://helm.elastic.co"
  version: ">0.0.1"
  condition: logstash.install
- name: opensearch-dashboards
  repository: https://opensearch-project.github.io/helm-charts
  version: ">0.0.1"
- name: opensearch
  version: ">0.0.1"
  repository: https://opensearch-project.github.io/helm-charts/
  condition: opensearch.install
