apiVersion: v2
name: qa-report-platform
description: Helm chart for report platform components
type: application
version: 0.0.1
appVersion: 1.0.0
keywords:
  - test results reporting service
  - test report dashboard
  - test automation reporting tools
  - test automation results dashboard
  - qa automation dashboard
  - qa metrics dashboard
  - automation test report
  - test analytics
  - test insights
  - test execution dashboard
home: https://groundzero.solutions
icon: https://groundzero.solutions
dependencies:
- name: logstash
  repository: "https://helm.elastic.co"
  version: ">0.0.1"
  condition: logstash.install
- name: opensearch-dashboards
  repository: https://opensearch-project.github.io/helm-charts
  version: ">0.0.1"
  condition: opensearch-dashboards.install
- name: opensearch
  version: ">0.0.1"
  repository: https://opensearch-project.github.io/helm-charts/
  condition: opensearch.install
- name: rabbitmq
  version: ">0.0.1"
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.install
- name: kafka
  version: ">0.0.1"
  repository: https://charts.bitnami.com/bitnami
  condition: kafka.install
- name: kafka-ui
  version: ">0.0.1"
  repository: https://provectus.github.io/kafka-ui-charts
  condition: kafka-ui.install
- name: ingress-nginx
  version: ">0.0.1"
  repository: https://kubernetes.github.io/ingress-nginx
  condition: ingress-nginx.install
- name: strimzi-kafka-operator
  version: ">0.0.1"
  repository: https://strimzi.io/charts
  condition: strimzi-kafka-operator.install
