
# https://github.com/elastic/helm-charts/blob/main/logstash/values.yaml
logstash:
  persistence:
    enabled: false
  logstashConfig:
   logstash.yml: |
     http:
       host: 0.0.0.0
  logstashPipeline:
   logstash.conf: |
      input {
        beats {
          port => 5044
        }
      }

      output {
        stdout {
          codec => rubydebug
          # opensearch-cluster-master-0
        }
      }

  extraPorts:
    - name: test-results
      containerPort: 5044

  service:
    # annotations: {}
    type: ClusterIP
    # loadBalancerIP: ""
    ports:
      - name: test-results
        port: 5044
        protocol: TCP
        targetPort: 5044

opensearch-dashboards:
  opensearchHosts: "http://opensearch-cluster-master:9200"
  image:
    tag: "2.18.0"
  extraEnvs:
  - name: "DISABLE_SECURITY_PLUGIN"
    value: "true"
  config:
    opensearch_dashboards.yml: |
      # opensearch_security.multitenancy.enabled: true
      # opensearch_security.multitenancy.tenants.preferred: [Private, Global]
      # opensearch_security.readonly_mode.roles: [kibana_read_only]

      opensearch_security.cookie.secure: false
      # server.host: '0.0.0.0'

      # Default OpenSearch Dashboards configuration from docker image of Dashboards
      opensearch_security.enabled: false

  # ingress:
  #   enabled: true
  #   ingressClassName: nginx
  #   annotations:
  #     kubernetes.io/ingress.class: "nginx"
  #   hosts:
  #     - host: rp-dev1.palethorpe.biz
  #       paths:
  #         - path: /xx
  #           backend:
  #             serviceName: ""
  #             servicePort: ""
  #   tls:
  #   - secretName: rp-dev1-tls
  #     hosts:
  #       - rp-dev1.palethorpe.biz

  