apiVersion: v1
kind: ConfigMap
metadata:
  name: ls-pipeline-20-process-split-test-case-cm
data:
  20-process-split-test-case.conf: |
    input {
      pipeline { address => "20-process-split-test-case" }
    }
    
    filter {
      split { field => "[test-cases]" }

      ruby  {
        code => '
          h = event.get("[test-cases]")
          h.each {|k,v| event.set(k,v) } if h
      '}

      mutate {
        remove_field => [ "[test-cases]", "[test-run]", "[test-suites]", "[event]", "[url]", "[user_agent]", "[http]", "[host]" ]
      }

    }

  30_output_tosca.conf: |
    output { pipeline { send_to => ["30-output-common"] } }
