apiVersion: v1
kind: ConfigMap
metadata:
  name: ls-pipeline-20-process-split-test-case-cm
data:
  20-process-split-test-case.conf: |
    input {
      pipeline { address => "20-process-split-test-case" }
    }
    
    filter {
      split { field => "[test-cases]" }

      ruby  {
        code => '
          h = event.get("[test-cases]")
          h.each {|k,v| event.set(k,v) } if h
      '}

      ruby {
        code => '
          t = Time.at(event.get("@timestamp").to_f)
          suffix = t.strftime("%Y%m%d%H%M%S")
          event.set("[@metadata][id_suffix]", suffix)

          suffix = t.strftime("%Y-%m")
          event.set("[@metadata][index_suffix]", "-" + suffix)
        '
      }
    }

  30_output_tosca.conf: |
    output { pipeline { send_to => ["30-output-common"] } }
