apiVersion: v1
kind: ConfigMap
metadata:
  name: ls-pipeline-30-output-common-cm
data:
  30_common.conf: |
    input {
      pipeline { address => "30-output-common" }
    }

    output {

      if "debug" in [tags] {
        stdout { codec  => rubydebug { metadata => true } }
      }
      
      if [product] =~ "Tosca" {

        # Workaround: Do not allo-w updates to execution-test-case-log 
        if [@metadata][id] and [object-type] == "execution-test-case-log" {
        
          opensearch {
            codec => json

            hosts => ["https://opensearch-cluster-master:9200"]
            index => "%{[@metadata][index_prefix]}%{[@metadata][index_suffix]}"

            user => "admin"
            password => "${OS_PASSWORD}"
            ssl => true
            ssl_certificate_verification => false
            
            action => "create"

            document_id => "%{[@metadata][id]}"
          }

        } else if [@metadata][id] {
        
          opensearch {
            codec => json

            hosts => ["https://opensearch-cluster-master:9200"]
            index => "%{[@metadata][index_prefix]}%{[@metadata][index_suffix]}"

            user => "admin"
            password => "${OS_PASSWORD}"
            ssl => true
            ssl_certificate_verification => false
            
            # action => "create"

            document_id => "%{[@metadata][id]}"
          }

        } else {
          opensearch {
            codec => json

            hosts => ["https://opensearch-cluster-master:9200"]
            index => "%{[@metadata][index_prefix]}%{[@metadata][index_suffix]}"

            user => "admin"
            password => "${OS_PASSWORD}"
            ssl => true
            ssl_certificate_verification => false
            
            # action => "create"
          }

        }
      } else if "nunit" in [@metadata][input][http][request][headers][tags]  {

          opensearch {
            codec => json

            hosts => ["https://opensearch-cluster-master:9200"]
            index => "nunit-%{[@metadata][index_suffix]}"

            user => "admin"
            password => "${OS_PASSWORD}"
            ssl => true
            ssl_certificate_verification => false
            
            # action => "create"
          }

      } else {

        # Catch other messages to 'raw' index

        opensearch {
          # codec => json

          hosts => ["https://opensearch-cluster-master:9200"]
          index => "raw-other"

          user => "admin"
          password => "${OS_PASSWORD}"
          ssl => true
          ssl_certificate_verification => false
        }
      }

    }
