apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-install-files-cm
data:
  # PUT _template/tosca-template
  tosca-template.json: |
    {
        "order": 5,
        "index_patterns": [
            "tosca-*",
            "backup-tosca"
        ],
        "settings": {
            "index": {
                "number_of_shards": 1,
                "number_of_replicas": 0,
                "refresh_interval": "5s"
            }
        },
        "mappings": {
            "numeric_detection": true,
            "dynamic": true,
            "dynamic_templates": [
                {
                    "properties_as_keywords": {
                        "match_mapping_type": "*",
                        "path_match": [
                            "properties.name",
                            "properties.value",
                            "test-case-execution-log.properties.name",
                            "test-case-execution-log.properties.value",
                            "test-case.properties.name",
                            "test-case.properties.value",
                            "execution-entry.properties.name",
                            "execution-entry.properties.value",
                            "execution-list.properties.name",
                            "execution-list.properties.value",
                            "execution-log.properties.name",
                            "execution-log.properties.value",
                            "*.properties.name",
                            "*.properties.value"
                        ],
                        "mapping": {
                            "type": "keyword",
                            "ignore_above": 512
                        }
                    }
                },
                {
                    "uniqueids_as_keywords": {
                        "match_mapping_type": "*",
                        "path_match": [
                            "*unique-id.*",
                            "*.unique-id",
                            "*parent-surrogate-num*",
                            "parent-surrogate-num"
                        ],
                        "mapping": {
                            "type": "keyword"
                        }
                    }
                },
                {
                    "date_matches": {
                        "match_mapping_type": "*",
                        "path_match": [
                            "*start-time*",
                            "*end-time*",
                            "*created-at*",
                            "*modified-at*"
                        ],
                        "mapping": {
                            "type": "date"
                        }
                    }
                },
                {
                    "strings": {
                        "mapping": {
                            "ignore_above": 512,
                            "type": "keyword"
                        },
                        "match_mapping_type": "string"
                    }
                }

            ],
            "date_detection": true,
            "properties": {

                "disk": {
                    "properties": {
                    "device-id": {
                        "type": "keyword",
                        "ignore_above": 512
                    },
                    "size-gb": {
                        "type": "float"
                    },
                    "free-space-gb": {
                        "type": "float"
                    },
                    "used-space-gb": {
                        "type": "float"
                    },
                    "percent-used": {
                        "type": "float"
                    }
                    }
                },

                "log-info": {
                    "type": "text"
                },
                "object-hash": {
                    "type": "keyword"
                },
                "flattened": {
                    "type": "text"
                },
                "aggregated-description": {
                    "type": "text"
                },
                "description": {
                    "type": "text"
                },
                "name": {
                    "type": "keyword"
                },
                "@timestamp": {
                    "type": "date"
                },
                "start-time": {
                    "type": "date"
                },
                "end-time": {
                    "type": "date"
                },
                "index_prefix": {
                    "type": "keyword"
                },
                "parent-surrogate-num": {
                    "type": "keyword"
                },
                "unique-id": {
                    "type": "keyword"
                },
                "execution-list-unique-id": {
                    "type": "keyword"
                },
                "test-case-unique-id": {
                    "type": "keyword"
                },
                "folder": {
                    "type": "text",
                    "fields": {
                        "raw": {
                            "type": "keyword",
                            "ignore_above": 2048
                        }
                    }
                },
                "error-messages": {
                    "type": "text"
                },
                "tags": {
                    "type": "keyword"
                },
                "execution-list-entry-unique-id": {
                    "type": "keyword"
                },
                "execution-entry": {
                    "properties": {
                        "created-at": {
                            "type": "date"
                        },
                        "execution-test-case-log-execution-session-id": {
                            "type": "keyword"
                        },
                        "execution-test-case-log-unique-id": {
                            "type": "keyword"
                        },
                        "modified-at": {
                            "type": "date"
                        },
                        "parent-surrogate-num": {
                            "type": "keyword"
                        },
                        "unique-id": {
                            "type": "keyword"
                        }
                    }
                },
                "test-case": {
                    "properties": {
                        "created-at": {
                            "type": "date"
                        },
                        "modified-at": {
                            "type": "date"
                        },
                        "parent-surrogate-num": {
                            "type": "keyword"
                        },
                        "unique-id": {
                            "type": "keyword"
                        },
                        "properties": {
                            "properties": {
                                "name": {
                                "type": "keyword",
                                "ignore_above": 512
                                },
                                "value": {
                                "type": "keyword",
                                "ignore_above": 512
                                }
                            }
                        }
                    }
                },
                "execution-log": {
                    "properties": {
                        "created-at": {
                            "type": "date"
                        },
                        "modified-at": {
                            "type": "date"
                        },
                        "start-time": {
                            "type": "date"
                        },
                        "parent-surrogate-num": {
                            "type": "keyword"
                        },
                        "properties": {
                            "properties": {
                                "name": {
                                "type": "keyword",
                                "ignore_above": 512
                                },
                                "value": {
                                "type": "keyword",
                                "ignore_above": 512
                                }
                            }
                        },
                        "unique-id": {
                            "type": "keyword"
                        }
                    }
                },
                "execution-list": {
                    "properties": {
                        "created-at": {
                            "type": "date"
                        },
                    
                        "modified-at": {
                            "type": "date"
                        },
                        "parent-surrogate-num": {
                            "type": "keyword"
                        },
                        "project-id": {
                            "type": "keyword"
                        },
                        "properties": {
                            "properties": {
                                "name": {
                                    "type": "keyword",
                                    "ignore_above": 512
                                },
                                "value": {
                                    "type": "keyword",
                                    "ignore_above": 512
                                }
                            }
                        },
                        "unique-id": {
                            "type": "keyword"
                        }
                    }
                }
            }
        },
        "aliases": {}
    }
    
  # PUT   _template/tosca-healthcheck
  tosca-healthchecks.json: |
    {
        "order": 5,
        "index_patterns": [
            "tosca*healthcheck*",
            "backup-*healthcheck*"
        ],
        "settings": {
            "index": {
                "number_of_shards": 1,
                "number_of_replicas": 0,
                "refresh_interval": "5s"
            }
        },
        "mappings": {
            "numeric_detection": true,
            "dynamic": true,
            "dynamic_templates": [
                {
                    "strings": {
                        "mapping": {
                            "ignore_above": 512,
                            "type": "keyword"
                        },
                        "match_mapping_type": "string"
                    }
                }
            ],
            "date_detection": true,
            "properties": {
                "description": {
                    "type": "text"
                },
                "name": {
                    "type": "keyword"
                },
                "@timestamp": {
                    "type": "date"
                },
                "start-time": {
                    "type": "date"
                },
                "end-time": {
                    "type": "date"
                },
                "tags": {
                    "type": "keyword"
                }
                
            }
        },
        "aliases": {}
    }

  # PUT _index_template/tosca-system-info-template
  tosca-systeminfo.json: |
    {
    "index_patterns": ["tosca-system-info-*"],
    "order": 10,
    "template": {
        "mappings": {
        "dynamic": true,
        "date_detection": true,
        "numeric_detection": true,
        "dynamic_templates": [
            {
            "properties_as_keywords": {
                "path_match": "*properties.name",
                "mapping": {
                "type": "keyword",
                "ignore_above": 512
                }
            }
            },
            {
            "properties_values_as_keywords": {
                "path_match": "*properties.value",
                "mapping": {
                "type": "keyword",
                "ignore_above": 512
                }
            }
            },
            {
            "uniqueids_as_keywords": {
                "path_match": "*unique-id*",
                "mapping": {
                "type": "keyword"
                }
            }
            },
            {
            "parent_surrogate_as_keywords": {
                "path_match": "*parent-surrogate-num*",
                "mapping": {
                "type": "keyword"
                }
            }
            },
            {
            "date_matches": {
                "path_match": "*start-time|*end-time|*created-at|*modified-at",
                "mapping": {
                "type": "date"
                }
            }
            },
            {
            "strings": {
                "match_mapping_type": "string",
                "mapping": {
                "type": "keyword",
                "ignore_above": 512
                }
            }
            }
        ],
        "properties": {
            "@timestamp": { "type": "date" },
            "@version": { "type": "long" },
            "timestamp": { "type": "date" },
            "start-time": { "type": "date" },
            "end-time": { "type": "date" },
            "eventtime": { "type": "date" },
            "action": { "type": "keyword", "ignore_above": 512 },
            "script": { "type": "keyword", "ignore_above": 512 },
            "description": { "type": "text" },
            "aggregated-description": { "type": "text" },
            "log-info": { "type": "text" },
            "tags": { "type": "keyword" },
            "index_prefix": { "type": "keyword" },
            "name": { "type": "keyword" },
            "product": { "type": "keyword", "ignore_above": 512 },
            "cust-code": { "type": "keyword", "ignore_above": 512 },
            "country": { "type": "keyword", "ignore_above": 512 },
            "agent": {
            "properties": {
                "ephemeral_id": { "type": "keyword", "ignore_above": 512 },
                "id": { "type": "keyword", "ignore_above": 512 },
                "name": { "type": "keyword", "ignore_above": 512 },
                "type": { "type": "keyword", "ignore_above": 512 },
                "version": { "type": "keyword", "ignore_above": 512 }
            }
            },
            "ecs": {
            "properties": {
                "version": { "type": "keyword", "ignore_above": 512 }
            }
            },
            "computer-system": {
            "properties": {
                "manufacturer": { "type": "keyword", "ignore_above": 512 },
                "model": { "type": "keyword", "ignore_above": 512 },
                "number-of-logical-processors": { "type": "long" },
                "number-of-processors": { "type": "long" },
                "total-physical-memory": { "type": "long" }
            }
            },
            "cpu": {
            "properties": {
                "name": { "type": "keyword", "ignore_above": 512 },
                "max-clock-speed": { "type": "long" },
                "current-clock-speed": { "type": "long" },
                "load-percentage": { "type": "long" }
            }
            },
            "memory": {
            "properties": {
                "available-ram-mb": { "type": "float" },
                "used-ram-gb": { "type": "float" },
                "total-ram-gb": { "type": "float" },
                "percent-used": { "type": "long" }
            }
            },
            "disk": {
            "properties": {
                "device-id": { "type": "keyword", "ignore_above": 512 },
                "size-gb": { "type": "float" },
                "free-space-gb": { "type": "float" },
                "used-space-gb": { "type": "float" },
                "percent-used": { "type": "float" }
            }
            },
            "log": {
            "properties": {
                "offset": { "type": "long" },
                "file": {
                "properties": {
                    "path": { "type": "keyword", "ignore_above": 512 },
                    "fingerprint": { "type": "keyword", "ignore_above": 512 },
                    "idxhi": { "type": "long" },
                    "idxlo": { "type": "long" },
                    "vol": { "type": "long" }
                }
                }
            }
            },
            "folder": {
            "type": "text",
            "fields": {
                "raw": { "type": "keyword", "ignore_above": 2048 }
            }
            }
        }
        }
    }
    }